language: php
php:
 - 5.3
 - 5.4
 - 5.5

branches:
  - master

matrix:
  include:
    - php: 5.3
      env: VARIA=true
      before_script:
       - git clone https://github.com/Elgg/Elgg.git ../Elgg && cd ../Elgg && cd ../Elgg
       - git checkout 1.9
       - mv ../elgg_dropzone mod/elgg_dropzone
       - node -v
       - pear install pear/PHP_CodeSniffer
       - mkdir ../elgg-coding-standards
       - git clone https://github.com/Elgg/elgg-coding-standards.git ../elgg-coding-standards/
       - phpenv rehash
       - npm install -g karma@0.8
       - sudo easy_install "Sphinx==1.1.3"
       - wget https://scrutinizer-ci.com/ocular.phar
       - curl -sS https://getcomposer.org/installer | php
      script:
       - phpcs --standard=../elgg-coding-standards/elgg.xml --warning-severity=0 --ignore=*/tests/*,*/upgrades/*,*/deprecated* engine/classes engine/lib
       - karma start js/tests/karma.conf.js --single-run
       - sphinx-build -b html -nW docs docs/_build/html
         # Flags used here, not in `make html`:
         #  -n   Run in nit-picky mode. Currently, this generates warnings for all missing references.
         #  -W   Turn warnings into errors. This means that the build stops at the first warning and sphinx-build exits with exit status 1.
       - phpunit --coverage-clover=coverage.clover
       - php composer.phar validate
      after_script:
       - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

services:
 - mysql

before_script:
 - mysql -e 'create database elgg;'
 - echo "USE mysql; UPDATE user SET password=PASSWORD('password') WHERE user='root'; FLUSH PRIVILEGES;" | mysql -u root
 - mkdir "${HOME}/elgg_data/"
 - php -f ./Elgg/install/cli/travis_installer.php
 - php -f ./Elgg/mod/elgg_dropzone/travis/activate.php

script:
 - phpunit
 - php -f ./Elgg/engine/tests/suite.php

notifications:
  email:
    secure: exC/ws07lLOj3Y43C89jiaKpyB8Yt7DPGSCShV4R3Wkw/hVVzjxt1BinPxzsyL5DC7APUMcTHGOhDB2oCE4ynDE6o6L9bH79fc+V8IYAiNaEIGL0AOuHdnRdGN9GMrr2jv78cZ5MctuUTkeYLaoOEyDGHmkMhqa6SufIDAY8b58=